package:
  name: album
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 1

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

  entry_points:
    - album = album.server:run

requirements:
  build:
    - python

  run:
    - python
    - bokeh
    - flask
    - databroker >=0.3.0
    - numpy

test:
  imports:
    - album
